//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularUICalendarCRUd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventCalender
    {
        public int EventID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime StartAt { get; set; }
        public System.DateTime EndAt { get; set; }
        public bool IsFullDay { get; set; }
        public int PersonId { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
